spring:
  datasource:
    url: jdbc:h2:mem:testedbglicare
    driver-class-name: org.h2.Driver
    username: glicare
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
